# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-RuledValidator
version:      0.10
version_from: lib/Data/RuledValidator.pm
installdirs:  site
requires:
    Class::Inspector:              0
    Email::Valid:                  0.15
    Email::Valid::Loose:           0.04
    File::Slurp:                   0.01
    List::MoreUtils:               0
    Test::Base:                    0
    UNIVERSAL::require:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
